Feature: mod-finance integration tests

  Background:
    * url baseUrl
    * def requiredApplications = ['app-acquisitions', 'app-platform-complete', 'app-platform-minimal', 'app-fqm', 'app-consortia']

    * table userPermissions
      | name                                                    |
      | 'acquisitions-units.memberships.item.delete' |
      | 'acquisitions-units.memberships.item.post' |
      | 'acquisitions-units.units.item.post' |
      | 'acquisitions-units-storage.memberships.collection.get' |
      | 'acquisitions-units-storage.memberships.item.put' |
      | 'acquisitions-units-storage.memberships.item.delete' |
      | 'acquisitions-units-storage.memberships.item.post' |
      | 'acquisitions-units-storage.units.item.get' |
      | 'acquisitions-units-storage.units.item.post' |
      | 'acquisitions-units-storage.units.item.put' |
      | 'acquisitions-units-storage.units.item.delete' |
      | 'configuration.entries.collection.get' |
      | 'configuration.entries.item.delete' |
      | 'configuration.entries.item.post' |
      | 'configuration.entries.item.put' |
      | 'finance.budgets.collection.get' |
      | 'finance.budgets.item.delete' |
      | 'finance.budgets.item.get' |
      | 'finance.budgets.item.post' |
      | 'finance.budgets.item.put' |
      | 'finance.budgets-expense-classes-totals.collection.get' |
      | 'finance.expense-classes.item.post' |
      | 'finance.ledger-rollovers-budgets.item.get' |
      | 'finance.funds.budget.item.get' |
      | 'finance.finance-data.collection.get' |
      | 'finance.fiscal-years.item.delete' |
      | 'finance.fiscal-years.item.get' |
      | 'finance.fiscal-years.item.post' |
      | 'finance.fiscal-years.item.put' |
      | 'finance.fund-types.item.post' |
      | 'finance.funds.collection.get' |
      | 'finance.funds.item.get' |
      | 'finance.funds.item.put' |
      | 'finance.groups-expense-classes-totals.collection.get' |
      | 'finance.groups-expense-classes-totals.collection.post' |
      | 'finance.groups.item.post' |
      | 'finance.group-fiscal-year-summaries.collection.get' |
      | 'finance.group-fiscal-year-summaries.collection.post' |
      | 'finance.group-fund-fiscal-years.item.post' |
      | 'finance.ledger-rollovers-budgets.collection.get' |
      | 'finance.ledger-rollovers-budgets.item.get' |
      | 'finance.ledger-rollovers-errors.collection.get' |
      | 'finance.ledger-rollovers-logs.collection.get' |
      | 'finance.ledger-rollovers-logs.item.get' |
      | 'finance.ledger-rollovers.item.post' |
      | 'finance.ledger-rollovers-progress.collection.get' |
      | 'finance.ledger-rollovers-progress.item.put' |
      | 'finance.ledgers.current-fiscal-year.item.get' |
      | 'finance.ledgers.collection.get' |
      | 'finance.ledgers.item.delete' |
      | 'finance.ledgers.item.get' |
      | 'finance.ledgers.item.post' |
      | 'finance.release-encumbrance.item.post' |
      | 'finance.transactions.batch.execute' |
      | 'finance.transactions.collection.get' |
      | 'finance.transactions.item.delete' |
      | 'finance.transactions.item.get' |
      | 'finance-storage.budget-expense-classes.collection.get' |
      | 'finance-storage.budget-expense-classes.item.post' |
      | 'finance-storage.group-fund-fiscal-years.item.post' |
      | 'finance-storage.budgets.item.post' |
      | 'finance-storage.funds.item.delete' |
      | 'finance-storage.funds.item.post' |
      | 'finance-storage.budgets.item.get' |
      | 'finance-storage.group-fund-fiscal-years.collection.get' |
      | 'finance-storage.ledger-rollovers-errors.collection.get' |
      | 'finance-storage.ledger-rollovers.item.delete' |
      | 'finance-storage.ledgers.item.post' |
      | 'finance-storage.transactions.batch.execute' |
      | 'finance-storage.transactions.collection.get' |
      | 'finance.finance-data.collection.put' |
      | 'inventory-storage.contributor-name-types.item.post' |
      | 'inventory-storage.electronic-access-relationships.item.post' |
      | 'inventory-storage.holdings-sources.item.post' |
      | 'inventory-storage.holdings.item.post' |
      | 'inventory-storage.identifier-types.item.post' |
      | 'inventory-storage.instance-statuses.item.post' |
      | 'inventory-storage.instance-types.item.post' |
      | 'inventory-storage.loan-types.item.post' |
      | 'inventory-storage.location-units.campuses.item.post' |
      | 'inventory-storage.location-units.institutions.item.post' |
      | 'inventory-storage.location-units.libraries.item.post' |
      | 'inventory-storage.locations.item.post' |
      | 'inventory-storage.material-types.item.post' |
      | 'inventory-storage.service-points.item.post' |
      | 'inventory.instances.item.post' |
      | 'invoice.invoices.item.get' |
      | 'invoice.invoice-lines.item.post' |
      | 'invoice.invoices.item.post' |
      | 'invoice.invoices.item.put' |
      | 'organizations-storage.organizations.item.post' |
      | 'organizations.organizations.item.get' |
      | 'organizations.organizations.item.post' |
      | 'organizations.organizations.item.put' |
      | 'orders.check-in.collection.post' |
      | 'orders.collection.get' |
      | 'orders.item.approve' |
      | 'orders.item.delete' |
      | 'orders.item.get' |
      | 'orders.item.post' |
      | 'orders.item.put' |
      | 'orders.item.reopen' |
      | 'orders.item.unopen' |
      | 'orders.pieces.collection.get' |
      | 'orders.pieces.item.delete' |
      | 'orders.pieces.item.post' |
      | 'orders.po-lines.collection.get' |
      | 'orders.po-lines.item.delete' |
      | 'orders.po-lines.item.get' |
      | 'orders.po-lines.item.post' |
      | 'orders.po-lines.item.put' |
      | 'orders.re-encumber.item.post' |
      | 'orders-storage.module.all' |
      | 'orders-storage.order-invoice-relationships.collection.get' |
      | 'orders-storage.po-lines.item.get' |
      | 'orders-storage.po-lines.item.put' |
      | 'orders.titles.collection.get' |
      | 'orders.titles.item.post' |

  Scenario: create tenant and users for testing
    * def testUser = testAdmin
    Given call read('classpath:common/eureka/setup-users.feature')

  Scenario: init global data
    * call login testAdmin
    * callonce read('classpath:global/finances.feature')
    * callonce read('classpath:global/organizations.feature')
    * callonce read('classpath:global/configuration.feature')
    * callonce read('classpath:global/inventory.feature')