Feature: mod-data-import integration tests

  Background:
    * url baseUrl
    * configure readTimeout = 300000

    * table modules
      | name                        |
      | 'mod-login'                 |
      | 'mod-permissions'           |
      | 'mod-users'                 |
      | 'mod-users-bl'              |
      | 'mod-configuration'         |
      | 'mod-source-record-storage' |
      | 'mod-source-record-manager' |
      | 'mod-inventory-storage'     |
      | 'mod-di-converter-storage'  |
      | 'mod-inventory'             |
      | 'mod-data-export'           |
      | 'mod-data-import'           |
      | 'mod-organizations-storage' |
      | 'mod-invoice'               |
      | 'mod-invoice-storage'       |
      | 'mod-orders-storage'        |
      | 'mod-orders'                |
      | 'mod-finance'               |
      | 'mod-finance-storage'       |
      | 'mod-copycat'               |
      | 'mod-organizations'         |
      | 'mod-entities-links'        |
      | 'mod-quick-marc'            |

    * table userPermissions
      | name                                                                  |
      | 'acquisitions-units-storage.memberships.item.post'                    |
      | 'acquisitions-units-storage.units.item.post'                          |
      | 'change-manager.jobExecutions.children.collection.get'                |
      | 'change-manager.jobExecutions.item.get'                               |
      | 'change-manager.jobexecutions.delete'                                 |
      | 'converter-storage.actionprofile.collection.get'                      |
      | 'converter-storage.actionprofile.delete'                              |
      | 'converter-storage.actionprofile.post'                                |
      | 'converter-storage.jobprofile.collection.get'                         |
      | 'converter-storage.jobprofile.delete'                                 |
      | 'converter-storage.jobprofile.item.get'                               |
      | 'converter-storage.jobprofile.post'                                   |
      | 'converter-storage.mappingprofile.delete'                             |
      | 'converter-storage.mappingprofile.post'                               |
      | 'converter-storage.matchprofile.post'                                 |
      | 'copycat.imports.post'                                                |
      | 'copycat.profiles.collection.get'                                     |
      | 'copycat.profiles.item.put'                                           |
      | 'data-export.export.post'                                             |
      | 'data-export.file-definitions.item.get'                               |
      | 'data-export.file-definitions.item.post'                              |
      | 'data-export.file-definitions.upload.post'                            |
      | 'data-export.job-executions.collection.get'                           |
      | 'data-export.job-executions.items.download.get'                       |
      | 'data-export.job-profiles.item.post'                                  |
      | 'data-export.mapping-profiles.item.post'                              |
      | 'data-export.quick.export.post'                                       |
      | 'data-import.assembleStorageFile.post'                                |
      | 'data-import.datatypes.get'                                           |
      | 'data-import.downloadUrl.get'                                         |
      | 'data-import.fileExtensions.collection.get'                           |
      | 'data-import.fileExtensions.default.post'                             |
      | 'data-import.fileExtensions.delete'                                   |
      | 'data-import.fileExtensions.item.get'                                 |
      | 'data-import.fileExtensions.post'                                     |
      | 'data-import.fileExtensions.put'                                      |
      | 'data-import.jobexecution.cancel'                                     |
      | 'data-import.splitconfig.get'                                         |
      | 'data-import.upload.file.post'                                        |
      | 'data-import.uploadDefinitions.files.item.post'                       |
      | 'data-import.uploadDefinitions.item.get'                              |
      | 'data-import.uploadDefinitions.processFiles.item.post'                |
      | 'data-import.uploadUrl.item.get'                                      |
      | 'data-import.uploadUrl.subsequent.item.get'                           |
      | 'data-import.uploaddefinitions.files.delete'                          |
      | 'data-import.uploaddefinitions.post'                                  |
      | 'instance-authority-links.instances.collection.get'                   |
      | 'inventory-storage.authorities.collection.get'                        |
      | 'inventory-storage.authorities.item.delete'                           |
      | 'inventory-storage.authorities.item.get'                              |
      | 'inventory-storage.call-number-types.item.post'                       |
      | 'inventory-storage.contributor-name-types.collection.get'             |
      | 'inventory-storage.contributor-types.collection.get'                  |
      | 'inventory-storage.electronic-access-relationships.item.post'         |
      | 'inventory-storage.holdings-sources.item.get'                         |
      | 'inventory-storage.holdings-sources.item.post'                        |
      | 'inventory-storage.holdings-types.item.post'                          |
      | 'inventory-storage.holdings.collection.get'                           |
      | 'inventory-storage.holdings.item.get'                                 |
      | 'inventory-storage.holdings.item.post'                                |
      | 'inventory-storage.identifier-types.collection.get'                   |
      | 'inventory-storage.identifier-types.item.post'                        |
      | 'inventory-storage.ill-policies.item.post'                            |
      | 'inventory-storage.instance-statuses.item.post'                       |
      | 'inventory-storage.instance-types.item.post'                          |
      | 'inventory-storage.instances.collection.get'                          |
      | 'inventory-storage.instances.item.post'                               |
      | 'inventory-storage.item-note-types.item.post'                         |
      | 'inventory-storage.items.collection.get'                              |
      | 'inventory-storage.items.item.post'                                   |
      | 'inventory-storage.loan-types.item.post'                              |
      | 'inventory-storage.location-units.campuses.item.post'                 |
      | 'inventory-storage.location-units.institutions.item.post'             |
      | 'inventory-storage.location-units.libraries.item.post'                |
      | 'inventory-storage.locations.item.post'                               |
      | 'inventory-storage.material-types.item.post'                          |
      | 'inventory-storage.statistical-code-types.item.post'                  |
      | 'inventory-storage.statistical-codes.item.post'                       |
      | 'inventory.instances.collection.get'                                  |
      | 'inventory.instances.item.get'                                        |
      | 'inventory.instances.item.put'                                        |
      | 'inventory.items.collection.get'                                      |
      | 'inventory.items.item.get'                                            |
      | 'invoice-storage.invoice-lines.collection.get'                        |
      | 'invoice-storage.invoice-lines.item.get'                              |
      | 'invoice-storage.invoices.item.get'                                   |
      | 'invoice.invoice-lines.collection.get'                                |
      | 'invoice.invoice-lines.fund-distributions.validate'                   |
      | 'invoice.invoice-lines.item.delete'                                   |
      | 'invoice.invoice-lines.item.get'                                      |
      | 'invoice.invoice-lines.item.post'                                     |
      | 'invoice.invoice-lines.item.put'                                      |
      | 'invoice.invoice-number.item.get'                                     |
      | 'invoice.invoices.collection.get'                                     |
      | 'invoice.invoices.documents.collection.get'                           |
      | 'invoice.invoices.documents.item.delete'                              |
      | 'invoice.invoices.documents.item.get'                                 |
      | 'invoice.invoices.documents.item.post'                                |
      | 'invoice.invoices.fiscal-years.collection.get'                        |
      | 'invoice.invoices.item.delete'                                        |
      | 'invoice.invoices.item.get'                                           |
      | 'invoice.invoices.item.post'                                          |
      | 'invoice.invoices.item.put'                                           |
      | 'invoice.item.approve.execute'                                        |
      | 'invoice.item.cancel.execute'                                         |
      | 'invoice.item.pay.execute'                                            |
      | 'invoices.acquisitions-units-assignments.create.execute'              |
      | 'invoices.acquisitions-units-assignments.manage.execute'              |
      | 'mapping-metadata.item.get'                                           |
      | 'mapping-metadata.type.item.get'                                      |
      | 'mapping-rules.get'                                                   |
      | 'mapping-rules.restore'                                               |
      | 'mapping-rules.update'                                                |
      | 'marc-records-editor.item.get'                                        |
      | 'marc-records-editor.item.put'                                        |
      | 'metadata-provider.jobExecutions.collection.get'                      |
      | 'metadata-provider.jobExecutions.users.collection.get'                |
      | 'metadata-provider.jobLogEntries.collection.get'                      |
      | 'metadata-provider.jobLogEntries.records.item.get'                    |
      | 'metadata-provider.jobSummary.item.get'                               |
      | 'metadata-provider.journalRecords.collection.get'                     |
      | 'orders-storage.settings.collection.get'                              |
      | 'orders-storage.settings.item.post'                                   |
      | 'orders-storage.titles.item.get'                                      |
      | 'orders.item.get'                                                     |
      | 'orders.item.post'                                                    |
      | 'orders.item.put'                                                     |
      | 'orders.po-lines.item.get'                                            |
      | 'orders.po-lines.item.post'                                           |
      | 'organizations-storage.organizations.item.post'                       |
      | 'organizations.organizations.collection.get'                          |
      | 'search.authorities.collection.get'                                   |
      | 'source-storage.records.formatted.item.get'                           |
      | 'source-storage.records.item.get'                                     |
      | 'source-storage.source-records.collection.get'                        |
      | 'source-storage.source-records.item.get'                              |
      | 'users.collection.get'                                                |
      | 'inventory.instances.item.mark-deleted.delete'                        |


  Scenario: create tenant and users for testing
    * call read('classpath:common/eureka/setup-users.feature')
    * eval java.lang.System.setProperty('testUserId', karate.get('userId'))
    * def res = call createAdditionalUser { testUser: '#(testUser2)', userPermissions: '#(userPermissions)' }

  Scenario: init global data
    * call login testUser

    * callonce read('classpath:promin/data-import/global/mod_inventory_init_data.feature')
    * callonce read('classpath:promin/data-import/global/init-acquisition-data.feature')
