@parallel=false
Feature: edge-orders integration tests

  Background:
    * url baseUrl
    * table modules
      | name                        |
      | 'mod-permissions'           |
      | 'mod-configuration'         |
      | 'mod-login'                 |
      | 'mod-users'                 |
      | 'mod-organizations-storage' |
      | 'mod-organizations'         |
      | 'mod-inventory-storage'     |
      | 'mod-inventory'             |
      | 'mod-finance-storage'       |
      | 'mod-finance'               |
      | 'mod-orders-storage'        |
      | 'mod-orders'                |
      | 'mod-ebsconet'              |
      | 'mod-gobi'                  |

    * table userPermissions
      | name                                                          |
      | 'orders-storage.routing-lists.item.post'                      |
      | 'orders-storage.settings.item.post'                           |
      | 'orders-storage.pieces.collection.get'                        |
      | 'orders-storage.po-lines.item.put'                            |
      | 'orders-storage.po-lines.item.post'                           |
      | 'orders-storage.po-lines.item.get'                            |
      | 'orders-storage.claiming.process.execute'                     |
      | 'orders-storage.titles.item.get'                              |
      | 'orders-storage.purchase-orders.item.get'                     |
      | 'orders-storage.titles.collection.get'                        |
      | 'orders-storage.configuration.prefixes.collection.get'        |
      | 'orders-storage.configuration.suffixes.collection.get'        |
      | 'orders-storage.po-lines.collection.get'                      |
      | 'orders.acquisitions-units-assignments.assign'                |
      | 'orders.acquisitions-units-assignments.manage'                |
      | 'orders.acquisition-method.item.post'                         |
      | 'orders.acquisition-units.bypass.execute'                     |
      | 'orders.bind-pieces.item.delete'                              |
      | 'orders.bind-pieces.collection.post'                          |
      | 'orders.re-encumber.item.post'                                |
      | 'orders.routing-lists.item.put'                               |
      | 'orders.routing-lists.item.delete'                            |
      | 'orders.routing-lists.collection.get'                         |
      | 'orders.routing-lists.item.post'                              |
      | 'orders.routing-lists.item.get'                               |
      | 'orders.titles.item.get'                                      |
      | 'orders.titles.item.post'                                     |
      | 'orders.titles.item.put'                                      |
      | 'orders.titles.collection.get'                                |
      | 'orders.pieces.item.put'                                      |
      | 'orders.pieces.item.get'                                      |
      | 'orders.pieces.collection.post'                               |
      | 'orders.pieces.collection.put'                                |
      | 'orders.pieces.item.delete'                                   |
      | 'orders.pieces.item.post'                                     |
      | 'orders.pieces.collection.get'                                |
      | 'orders.po-lines.item.get'                                    |
      | 'orders.po-lines.item.post'                                   |
      | 'orders.po-lines.item.put'                                    |
      | 'orders.po-lines.item.delete'                                 |
      | 'orders.po-lines.collection.get'                              |
      | 'orders.item.get'                                             |
      | 'orders.item.post'                                            |
      | 'orders.item.put'                                             |
      | 'orders.item.reopen'                                          |
      | 'orders.item.unopen'                                          |
      | 'orders.item.delete'                                          |
      | 'orders.receiving.collection.post'                            |
      | 'orders.check-in.collection.post'                             |
      | 'orders.collection.get'                                       |
      | 'orders.item.approve'                                         |
      | 'organizations-storage.organizations.item.post'               |
      | 'organizations.organizations.item.get'                        |
      | 'organizations.organizations.item.post'                       |
      | 'organizations.organizations.item.put'                        |
      | 'configuration.entries.collection.get'                        |
      | 'configuration.entries.item.delete'                           |
      | 'configuration.entries.item.post'                             |
      | 'configuration.entries.item.put'                              |
      | 'inventory.items.move.item.post'                              |
      | 'inventory.holdings.move.item.post'                           |
      | 'inventory-storage.holdings.item.get'                         |
      | 'inventory.items.item.get'                                    |
      | 'inventory.tenant-items.collection.get'                       |
      | 'inventory.items.collection.get'                              |
      | 'inventory.items-by-holdings-id.collection.get'               |
      | 'inventory.instances.collection.get'                          |
      | 'inventory-storage.holdings.retrieve.collection.post'         |
      | 'inventory.instances.item.put'                                |
      | 'inventory-storage.locations.item.post'                       |
      | 'inventory-storage.holdings-sources.item.post'                |
      | 'inventory-storage.service-points.item.post'                  |
      | 'inventory-storage.location-units.libraries.item.post'        |
      | 'inventory-storage.location-units.campuses.item.post'         |
      | 'inventory-storage.location-units.institutions.item.post'     |
      | 'inventory-storage.electronic-access-relationships.item.post' |
      | 'inventory-storage.contributor-name-types.item.post'          |
      | 'inventory-storage.material-types.item.post'                  |
      | 'inventory-storage.loan-types.item.post'                      |
      | 'inventory-storage.instance-statuses.item.post'               |
      | 'inventory-storage.identifier-types.item.post'                |
      | 'inventory-storage.instance-types.item.post'                  |
      | 'inventory-storage.holdings.item.post'                        |
      | 'inventory-storage.holdings.collection.get'                   |
      | 'inventory-storage.instances.item.get'                        |
      | 'inventory-storage.items.item.get'                            |
      | 'inventory.instances.item.post'                               |
      | 'finance-storage.budget-expense-classes.collection.get'       |
      | 'finance-storage.budget-expense-classes.item.post'            |
      | 'finance-storage.budgets.item.get'                            |
      | 'finance-storage.budgets.item.post'                           |
      | 'finance-storage.funds.item.delete'                           |
      | 'finance-storage.funds.item.post'                             |
      | 'finance-storage.group-fund-fiscal-years.collection.get'      |
      | 'finance-storage.group-fund-fiscal-years.item.post'           |
      | 'finance-storage.ledger-rollovers-errors.collection.get'      |
      | 'finance-storage.ledger-rollovers.item.delete'                |
      | 'finance-storage.ledgers.item.post'                           |
      | 'finance-storage.transactions.batch.execute'                  |
      | 'finance-storage.transactions.collection.get'                 |
      | 'finance.budgets-expense-classes-totals.collection.get'       |
      | 'finance.budgets.collection.get'                              |
      | 'finance.budgets.item.delete'                                 |
      | 'finance.budgets.item.get'                                    |
      | 'finance.budgets.item.post'                                   |
      | 'finance.budgets.item.put'                                    |
      | 'finance.expense-classes.item.post'                           |
      | 'finance.fiscal-years.item.delete'                            |
      | 'finance.fiscal-years.item.get'                               |
      | 'finance.fiscal-years.item.post'                              |
      | 'finance.fiscal-years.item.put'                               |
      | 'finance.fund-types.item.post'                                |
      | 'finance.funds.budget.item.get'                               |
      | 'finance.funds.collection.get'                                |
      | 'finance.funds.item.get'                                      |
      | 'finance.funds.item.put'                                      |
      | 'finance.finance-data.collection.get'                         |
      | 'finance.finance-data.collection.put'                         |
      | 'finance.group-fiscal-year-summaries.collection.get'          |
      | 'finance.groups-expense-classes-totals.collection.get'        |
      | 'finance.groups.item.post'                                    |
      | 'finance.ledger-rollovers-errors.collection.get'              |
      | 'finance.ledger-rollovers.item.post'                          |
      | 'finance.ledgers.collection.get'                              |
      | 'finance.ledgers.current-fiscal-year.item.get'                |
      | 'finance.ledgers.item.delete'                                 |
      | 'finance.ledgers.item.get'                                    |
      | 'finance.ledgers.item.post'                                   |
      | 'finance.release-encumbrance.item.post'                       |
      | 'finance.transactions.batch.execute'                          |
      | 'finance.transactions.collection.get'                         |
      | 'finance.transactions.item.get'                               |
      | 'finance.ledger-rollovers-budgets.collection.get'             |
      | 'finance.ledger-rollovers-budgets.item.get'                   |
      | 'finance.ledger-rollovers-logs.item.get'                      |
      | 'finance.ledger-rollovers-progress.collection.get'            |
      | 'finance.group-fund-fiscal-years.item.post'                   |
      | 'finance.ledger-rollovers-logs.collection.get'                |
      | 'finance.ledger-rollovers-progress.item.put'                  |
      | 'finance.expense-classes.collection.get'                      |
      | 'finance.expense-classes.item.get'                            |
      | 'acquisitions-units-storage.units.collection.get'             |
      | 'acquisitions-units-storage.memberships.collection.get'       |
      | 'ebsconet.orders.validate.get'                                |
      | 'ebsconet.order-lines.item.put'                               |
      | 'gobi.validate.item.get'                                      |
      | 'gobi.validate.item.post'                                     |
      | 'gobi.orders.item.post'                                       |
      | 'notes.item.post'                                             |
      | 'notes.item.delete'                                           |
      | 'note.links.collection.get'                                   |
      | 'note.types.collection.get'                                   |
      | 'modperms.orders.item.post'                                   |

    * def testTenant = 'testedgeorders'
    * def testUser = { tenant: '#(testTenant)', name: 'test-user', password: 'test' }

  Scenario: create tenant and users for testing
    * call read('classpath:common/eureka/setup-users.feature') { testTenant: '#(testTenant)', testUser: '#(testUser)' }

  Scenario: init global data
    * callonce read('classpath:global/inventory.feature') { testAdmin: '#(testUser)' }
    * callonce read('classpath:global/configuration.feature') { testAdmin: '#(testUser)' }
    * callonce read('classpath:global/finances.feature') { testAdmin: '#(testUser)' }
    * callonce read('classpath:global/organizations.feature') { testAdmin: '#(testUser)' }