stages:
  - name: Run tests
    steps:
      - runScriptConfig:
          image: maven:3-eclipse-temurin-17-alpine
          shellScript: sh ./runtests.sh ${PROJECT} ${ENVIRONMENT}
        envFrom:
          - sourceName: integration-tests
            sourceKey: project
            targetKey: PROJECT
          - sourceName: integration-tests
            sourceKey: environment
            targetKey: ENVIRONMENT
timeout: 60
notification: {}
