@parallel=false
Feature: Initialize mod-orders integration tests

  Background:
    * print karate.info.scenarioName
    * url baseUrl
    # Order of the modules below is important: mod-pubsub should come before mod-circulation
    # Including all only required modules is needed for dev env, where checkDepsDuringModInstall is false
    * table modules
      | name                        |
      | 'mod-audit'                 |
      | 'mod-settings'              |
      | 'mod-feesfines'             |
      | 'mod-finance'               |
      | 'mod-finance-storage'       |
      | 'mod-inventory'             |
      | 'mod-inventory-storage'     |
      | 'mod-login'                 |
      | 'mod-orders'                |
      | 'mod-orders-storage'        |
      | 'mod-organizations'         |
      | 'mod-organizations-storage' |
      | 'mod-permissions'           |
      | 'mod-pubsub'                |
      | 'mod-circulation'           |
      | 'mod-circulation-storage'   |
      | 'mod-tags'                  |
      | 'mod-template-engine'       |
      | 'mod-users'                 |

    * table userPermissions
      | name                                           |
      | 'inventory.instances.item.get'                 |
      | 'inventory.instances.item.delete'              |
      | 'inventory.instances.item.post'                |
      | 'inventory.instances.item.put'                 |
      | 'orders-storage.claiming.process.execute'      |
      | 'orders-storage.pieces.collection.get'         |
      | 'orders-storage.po-lines.item.get'             |
      | 'orders-storage.po-lines.item.post'            |
      | 'orders-storage.po-lines.item.put'             |
      | 'orders-storage.purchase-orders.item.post'     |
      | 'orders-storage.routing-lists.item.post'       |
      | 'orders-storage.settings.item.post'            |
      | 'orders.acquisition-method.item.post'          |
      | 'orders.acquisitions-units-assignments.assign' |
      | 'orders.acquisitions-units-assignments.manage' |
      | 'orders.bind-pieces.collection.post'           |
      | 'orders.bind-pieces.item.delete'               |
      | 'orders.check-in.collection.post'              |
      | 'orders.collection.get'                        |
      | 'orders.holding-detail.item.post'              |
      | 'orders.item.approve'                          |
      | 'orders.item.delete'                           |
      | 'orders.item.get'                              |
      | 'orders.item.post'                             |
      | 'orders.item.put'                              |
      | 'orders.item.reopen'                           |
      | 'orders.item.unopen'                           |
      | 'orders.pieces.collection.get'                 |
      | 'orders.pieces.collection.post'                |
      | 'orders.pieces.collection.put'                 |
      | 'orders.pieces.item.delete'                    |
      | 'orders.pieces.item.get'                       |
      | 'orders.pieces.item.post'                      |
      | 'orders.pieces.item.put'                       |
      | 'orders.po-lines.collection.get'               |
      | 'orders.po-lines.item.delete'                  |
      | 'orders.po-lines.item.get'                     |
      | 'orders.po-lines.item.post'                    |
      | 'orders.po-lines.item.put'                     |
      | 'orders.receiving.collection.post'             |
      | 'orders.re-encumber.item.post'                 |
      | 'orders.routing-lists.collection.get'          |
      | 'orders.routing-lists.item.delete'             |
      | 'orders.routing-lists.item.get'                |
      | 'orders.routing-lists.item.post'               |
      | 'orders.routing-lists.item.put'                |
      | 'orders.routing-lists-template.item.get'       |
      | 'orders.titles.collection.get'                 |
      | 'orders.titles.item.delete'                    |
      | 'orders.titles.item.get'                       |
      | 'orders.titles.item.post'                      |
      | 'orders.titles.item.put'                       |

    * table adminPermissions
      | name                                                          |
      | 'acquisition.invoice-line.events.get'                         |
      | 'acquisition.invoice.events.get'                              |
      | 'acquisition.order-line.events.get'                           |
      | 'acquisition.order.events.get'                                |
      | 'acquisition.piece.events.get'                                |
      | 'acquisition.piece.events.history.get'                        |
      | 'acquisitions-units.memberships.collection.get'               |
      | 'acquisitions-units.memberships.item.delete'                  |
      | 'acquisitions-units.memberships.item.get'                     |
      | 'acquisitions-units.memberships.item.post'                    |
      | 'acquisitions-units.memberships.item.put'                     |
      | 'acquisitions-units.units.item.post'                          |
      | 'acquisitions-units.units.item.put'                           |
      | 'addresstypes.item.post'                                      |
      | 'circulation-storage.loan-policies.collection.get'            |
      | 'circulation-storage.loan-policies.item.post'                 |
      | 'circulation-storage.patron-notice-policies.collection.get'   |
      | 'circulation-storage.patron-notice-policies.item.post'        |
      | 'circulation-storage.request-policies.collection.get'         |
      | 'circulation-storage.request-policies.item.post'              |
      | 'circulation.requests.item.get'                               |
      | 'circulation.requests.item.move.post'                         |
      | 'circulation.requests.item.post'                              |
      | 'circulation.rules.put'                                       |
      | 'orders-storage.settings.collection.get'                      |
      | 'orders-storage.settings.item.post'                           |
      | 'orders-storage.settings.item.put'                            |
      | 'finance-storage.budget-expense-classes.item.post'            |
      | 'finance-storage.ledger-rollovers-errors.collection.get'      |
      | 'finance-storage.ledger-rollovers-errors.item.delete'         |
      | 'finance-storage.ledger-rollovers-errors.item.post'           |
      | 'finance-storage.ledger-rollovers.item.post'                  |
      | 'finance-storage.transactions.collection.get'                 |
      | 'finance.budgets-expense-classes-totals.collection.get'       |
      | 'finance.budgets.collection.get'                              |
      | 'finance.budgets.item.delete'                                 |
      | 'finance.budgets.item.get'                                    |
      | 'finance.budgets.item.post'                                   |
      | 'finance.budgets.item.put'                                    |
      | 'finance.exchange-rate.item.get'                              |
      | 'finance.expense-classes.item.post'                           |
      | 'finance.fiscal-years.item.delete'                            |
      | 'finance.fiscal-years.item.get'                               |
      | 'finance.fiscal-years.item.post'                              |
      | 'finance.fiscal-years.item.put'                               |
      | 'finance.funds.budget.item.get'                               |
      | 'finance.funds.collection.get'                                |
      | 'finance.funds.item.get'                                      |
      | 'finance.funds.item.post'                                     |
      | 'finance.funds.item.put'                                      |
      | 'finance.fund-types.item.post'                                |
      | 'finance.group-fund-fiscal-years.item.post'                   |
      | 'finance.groups-expense-classes-totals.collection.get'        |
      | 'finance.ledger-rollovers-errors.collection.get'              |
      | 'finance.ledger-rollovers.item.post'                          |
      | 'finance.ledgers.collection.get'                              |
      | 'finance.ledgers.current-fiscal-year.item.get'                |
      | 'finance.ledgers.item.delete'                                 |
      | 'finance.ledgers.item.get'                                    |
      | 'finance.ledgers.item.post'                                   |
      | 'finance.transactions.batch.execute'                          |
      | 'finance.transactions.collection.get'                         |
      | 'finance.transactions.item.get'                               |
      | 'inventory-storage.contributor-name-types.item.post'          |
      | 'inventory-storage.electronic-access-relationships.item.post' |
      | 'inventory-storage.holdings-sources.item.post'                |
      | 'inventory-storage.holdings.collection.get'                   |
      | 'inventory-storage.holdings.item.get'                         |
      | 'inventory-storage.holdings.item.post'                        |
      | 'inventory-storage.holdings.retrieve.collection.post'         |
      | 'inventory-storage.identifier-types.item.post'                |
      | 'inventory-storage.instances.item.get'                        |
      | 'inventory-storage.instance-statuses.item.post'               |
      | 'inventory-storage.instance-types.item.post'                  |
      | 'inventory-storage.loan-types.item.post'                      |
      | 'inventory-storage.location-units.campuses.item.post'         |
      | 'inventory-storage.location-units.institutions.item.post'     |
      | 'inventory-storage.location-units.libraries.item.post'        |
      | 'inventory-storage.locations.item.post'                       |
      | 'inventory-storage.material-types.item.post'                  |
      | 'inventory-storage.service-points.item.post'                  |
      | 'inventory.holdings.move.item.post'                           |
      | 'inventory.instances.collection.get'                          |
      | 'inventory.instances.item.get'                                |
      | 'inventory.instances.item.delete'                             |
      | 'inventory.instances.item.post'                               |
      | 'inventory.instances.item.put'                                |
      | 'inventory.items-by-holdings-id.collection.get'               |
      | 'inventory.items.collection.get'                              |
      | 'inventory.items.item.get'                                    |
      | 'inventory.items.item.post'                                   |
      | 'inventory.items.item.put'                                    |
      | 'inventory.items.move.item.post'                              |
      | 'inventory.tenant-items.collection.get'                       |
      | 'lost-item-fees-policies.collection.get'                      |
      | 'lost-item-fees-policies.item.post'                           |
      | 'organizations.organizations.item.post'                       |
      | 'overdue-fines-policies.collection.get'                       |
      | 'overdue-fines-policies.item.post'                            |
      | 'tags.collection.get'                                         |
      | 'templates.item.post'                                         |
      | 'titles.acquisitions-units-assignments.assign'                |
      | 'titles.acquisitions-units-assignments.manage'                |
      | 'usergroups.item.post'                                        |
      | 'users.collection.get'                                        |
      | 'users.item.post'                                             |


  Scenario: Create tenant and test user
    * call read('classpath:common/eureka/setup-users.feature')

  Scenario: Create admin user
    * def v = call createAdditionalUser { testUser: '#(testAdmin)', userPermissions: '#(adminPermissions)' }

  Scenario: Init global data
    * call login testAdmin
    * callonce read('classpath:global/inventory.feature')
    * callonce read('classpath:global/configuration.feature')
    * callonce read('classpath:global/finances.feature')
    * callonce read('classpath:global/organizations.feature')
    * call login testUser
    * callonce read('classpath:global/orders.feature')
