Feature: mod-feesfines integration tests

  Background:
    * url baseUrl
    * table modules
      | name                                                      |
      | 'mod-login'                                               |
      | 'mod-permissions'                                         |
      | 'mod-users'                                               |
      | 'mod-users-bl'                                            |
      | 'mod-configuration'                                       |
      | 'mod-settings'                                            |
      | 'mod-pubsub'                                              |
      | 'mod-feesfines'                                           |
      | 'mod-inventory'                                           |
      | 'mod-inventory-storage'                                   |
      | 'mod-circulation'                                         |
      | 'mod-circulation-storage'                                 |
      | 'mod-calendar'                                            |
      | 'okapi'                                                   |

    * table userPermissions
      | name                                                      |
      | 'owners.item.get'                                         |
      | 'owners.item.post'                                        |
      | 'owners.item.put'                                         |
      | 'owners.item.delete'                                      |
      | 'owners.collection.get'                                   |
      | 'accounts.item.get'                                       |
      | 'accounts.item.post'                                      |
      | 'accounts.item.put'                                       |
      | 'accounts.item.delete'                                    |
      | 'accounts.collection.get'                                 |
      | 'feesfines.accounts.pay.item.post'                        |
      | 'feesfines.accounts-bulk.pay.item.post'                   |
      | 'feesfines.accounts.waive.item.post'                      |
      | 'feesfines.accounts-bulk.waive.item.post'                 |
      | 'feesfines.accounts.cancel.item.post'                     |
      | 'feesfines.accounts-bulk.cancel.item.post'                |
      | 'feesfines.accounts.refund.item.post'                     |
      | 'feesfines.accounts-bulk.refund.item.post'                |
      | 'feesfines.accounts.transfer.item.post'                   |
      | 'feesfines.accounts-bulk.transfer.item.post'              |
      | 'feesfines.accounts.check-pay.item.post'                  |
      | 'feesfines.accounts-bulk.check-pay.item.post'             |
      | 'feesfines.accounts-bulk.check-waive.item.post'           |
      | 'feesfines.accounts.check-waive.item.post'                |
      | 'accounts.check-transfer.post'                            |
      | 'accounts.check-refund.post'                              |
      | 'actual-cost-fee-fine-cancel.post'                        |
      | 'feefines.item.get'                                       |
      | 'feefines.item.post'                                      |
      | 'feefines.item.put'                                       |
      | 'feefines.item.delete'                                    |
      | 'feefines.collection.get'                                 |
      | 'feefineactions.item.get'                                 |
      | 'feefineactions.item.post'                                |
      | 'feefineactions.item.put'                                 |
      | 'feefineactions.item.delete'                              |
      | 'feefineactions.collection.get'                           |
      | 'feefine-reports.refund.post'                             |
      | 'lost-item-fees-policies.item.get'                        |
      | 'lost-item-fees-policies.item.post'                       |
      | 'lost-item-fees-policies.item.put'                        |
      | 'lost-item-fees-policies.item.delete'                     |
      | 'lost-item-fees-policies.collection.get'                  |
      | 'payments.item.post'                                      |
      | 'waives.item.post'                                        |
      | 'users.item.post'                                         |
      | 'transfers.item.post'                                     |
      | 'manualblocks.item.get'                                   |
      | 'manualblocks.item.post'                                  |
      | 'manualblocks.item.put'                                   |
      | 'manualblocks.item.delete'                                |
      | 'manualblocks.collection.get'                             |
      | 'manual-block-templates.item.get'                         |
      | 'manual-block-templates.item.post'                        |
      | 'manual-block-templates.item.put'                         |
      | 'manual-block-templates.item.delete'                      |
      | 'manual-block-templates.collection.get'                   |
      | 'overdue-fines-policies.item.get'                         |
      | 'overdue-fines-policies.item.post'                        |
      | 'overdue-fines-policies.item.put'                         |
      | 'overdue-fines-policies.item.delete'                      |
      | 'overdue-fines-policies.collection.get'                   |
      | 'inventory-storage.instance-types.item.post'              |
      | 'inventory-storage.contributor-name-types.item.post'      |
      | 'inventory-storage.locations.item.post'                   |
      | 'inventory-storage.service-points.item.post'              |
      | 'inventory-storage.location-units.institutions.item.post' |
      | 'inventory-storage.location-units.campuses.item.post'     |
      | 'inventory-storage.location-units.libraries.item.post'    |
      | 'inventory-storage.holdings.item.post'                    |
      | 'inventory-storage.holdings-sources.item.post'            |
      | 'inventory-storage.loan-types.item.post'                  |
      | 'inventory-storage.material-types.item.post'              |
      | 'inventory.items.item.get'                                |
      | 'inventory.items.item.post'                               |
      | 'inventory.instances.item.post'                           |
      | 'inventory.instances.item.put'                            |
      | 'inventory.instances.collection.get'                      |
      | 'circulation.check-out-by-barcode.post'                   |
      | 'circulation.check-in-by-barcode.post'                    |
      | 'circulation.loans.declare-item-lost.post'                |
      | 'circulation-storage.patron-notice-policies.item.post'    |
      | 'circulation-storage.request-policies.item.post'          |
      | 'circulation-storage.loan-policies.item.post'             |
      | 'circulation-storage.circulation-rules.put'               |
      | 'automated-patron-blocks.collection.get'                  |
      | 'usergroups.item.post'                                    |
      | 'login.item.post'                                         |
      | 'perms.permissions.get'                                   |
      | 'perms.users.item.post'                                   |

  Scenario: create tenant and users for testing
    Given call read('classpath:common/setup-users.feature')
