Feature: mod-feesfines integration tests

  Background:
    * url baseUrl


    * table userPermissions
      | name                                                      |
      | 'owners.item.get'                                               |
      | 'owners.item.post'                                              |
      | 'owners.item.put'                                               |
      | 'owners.item.delete'                                            |
      | 'owners.collection.get'                                         |
      | 'accounts.item.get'                                             |
      | 'accounts.item.post'                                            |
      | 'accounts.item.put'                                             |
      | 'accounts.item.delete'                                          |
      | 'accounts.collection.get'                                       |
      | 'feesfines.accounts.pay.post'                                   |
      | 'feesfines.accounts.waive.post'                                 |
      | 'feesfines.accounts.cancel.post'                                |
      | 'feesfines.accounts.refund.post'                                |
      | 'feesfines.accounts.transfer.post'                              |
      | 'feesfines.accounts.check-pay.post'                             |
      | 'feesfines.accounts-bulk.check-transfer.post'                   |
      | 'feesfines.accounts.check-waive.post'                           |
      | 'feesfines.accounts.check-transfer.post'                        |
      | 'feesfines.accounts.check-refund.post'                          |
      | 'actual-cost-fee-fine-cancel.post'                              |
      | 'feefines.item.get'                                             |
      | 'feefines.item.post'                                            |
      | 'feefines.item.put'                                             |
      | 'feefines.item.delete'                                          |
      | 'feefines.collection.get'                                       |
      | 'feefineactions.item.get'                                       |
      | 'feefineactions.item.post'                                      |
      | 'feefineactions.item.put'                                       |
      | 'feefineactions.item.delete'                                    |
      | 'feefineactions.collection.get'                                 |
      | 'feefine-reports.refund.post'                                   |
      | 'lost-item-fees-policies.item.get'                              |
      | 'lost-item-fees-policies.item.post'                             |
      | 'lost-item-fees-policies.item.put'                              |
      | 'lost-item-fees-policies.item.delete'                           |
      | 'lost-item-fees-policies.collection.get'                        |
      | 'payments.item.post'                                            |
      | 'waives.item.post'                                              |
      | 'users.item.post'                                               |
      | 'transfers.item.post'                                           |
      | 'manualblocks.item.get'                                         |
      | 'manualblocks.item.post'                                        |
      | 'manualblocks.item.put'                                         |
      | 'manualblocks.item.delete'                                      |
      | 'manualblocks.collection.get'                                   |
      | 'manual-block-templates.item.get'                               |
      | 'manual-block-templates.item.post'                              |
      | 'manual-block-templates.item.put'                               |
      | 'manual-block-templates.item.delete'                            |
      | 'manual-block-templates.collection.get'                         |
      | 'overdue-fines-policies.item.get'                               |
      | 'overdue-fines-policies.item.post'                              |
      | 'overdue-fines-policies.item.put'                               |
      | 'overdue-fines-policies.item.delete'                            |
      | 'overdue-fines-policies.collection.get'                         |
      | 'inventory-storage.instance-types.item.post'                    |
      | 'inventory-storage.contributor-name-types.item.post'            |
      | 'inventory-storage.locations.item.post'                         |
      | 'inventory-storage.service-points.item.post'                    |
      | 'inventory-storage.location-units.institutions.item.post'       |
      | 'inventory-storage.location-units.campuses.item.post'           |
      | 'inventory-storage.location-units.libraries.item.post'          |
      | 'inventory-storage.holdings.item.post'                          |
      | 'inventory-storage.holdings-sources.item.post'                  |
      | 'inventory-storage.loan-types.item.post'                        |
      | 'inventory-storage.material-types.item.post'                    |
      | 'inventory.items.item.get'                                      |
      | 'inventory.items.item.post'                                     |
      | 'inventory.instances.item.post'                                 |
      | 'inventory.instances.item.put'                                  |
      | 'inventory.instances.collection.get'                            |
      | 'circulation.check-out-by-barcode.post'                         |
      | 'circulation.check-in-by-barcode.post'                          |
      | 'circulation.loans.declare-item-lost.post'                      |
      | 'circulation-storage.patron-notice-policies.item.post'          |
      | 'circulation-storage.request-policies.item.post'                |
      | 'circulation-storage.loan-policies.item.post'                   |
      | 'circulation-storage.circulation-rules.put'                     |
      | 'patron-blocks.automated-patron-blocks.collection.get'          |
      | 'usergroups.item.post'                                          |
      | 'login.item.post'                                               |
      | 'perms.permissions.get'                                         |
      | 'perms.users.item.post'                                         |
      | 'feesfines.accounts-bulk.check-pay.post'                        |
      | 'feesfines.accounts-bulk.check-refund.post'                     |
      | 'circulation.rules.get'                                         |
      | 'circulation.rules.put'                                         |
      | 'actual-cost-record-storage.actual-cost-records.item.post'      |
      | 'okapi.proxy.tenants.timers.list'                               |
      | 'okapi.proxy.tenants.timers.patch'                              |
      | 'actual-cost-record-storage.actual-cost-records.collection.get' |
      | 'mod-settings.entries.collection.get'                           |
      | 'mod-settings.entries.item.post'                                |
      | 'mod-settings.entries.item.put'                                 |
      | 'mod-settings.entries.item.delete'                              |
      | 'mod-settings.entries.item.get'                                 |
      | 'mod-settings.global.read.mod-circulation'                      |
      | 'mod-settings.global.read.circulation'                          |
      | 'feesfines.accounts-bulk.check-waive.post'                      |
      | 'scheduler.item.put'                                            |
      | 'scheduler.collection.get'                                      |

  Scenario: create tenant and users for testing
    Given call read('classpath:common/eureka/setup-users.feature')
