Feature: Resend file from Minio to (S)FTP generated by an export job
  # parameters: jobId

  Background:
    * url baseUrl

  Scenario: resendExportJobFile
    Given path 'data-export-spring/jobs/' + jobId + '/resend'
    When method POST
    Then status 200
