Feature: Verify file content generated by an export job
  # parameters: jobId

  Background:
    * url baseUrl
    * configure retry = { count: 12, interval: 5000 }

  Scenario: verifyExportJobFile
    Given path 'data-export-spring/jobs', jobId
    And retry until response.status == 'SUCCESSFUL'
    When method GET
    Then status 200
    And match response.status == 'SUCCESSFUL'
    And match response.startTime == '#present'
    And match response.endTime == '#present'
    And assert response.files.length == 1
