Feature: mod-fqm-manager integration tests

  Background:
    * url baseUrl
    * table modules
      | name                        |
      | 'mod-login'                 |
      | 'mod-permissions'           |
      | 'mod-users'                 |
      | 'mod-inventory-storage'     |
      | 'mod-circulation'           |
      | 'mod-circulation-storage'   |
      | 'mod-fqm-manager'           |
      | 'mod-finance'               |
      | 'mod-finance-storage'       |
      | 'mod-linked-data'           |
      | 'mod-orders'                |
      | 'mod-orders-storage'        |
      | 'mod-organizations'         |
      | 'mod-organizations-storage' |
      | 'mod-entities-links'        |
      | 'mod-pubsub'                |
      | 'mod-patron-blocks'         |
      | 'mod-feesfines'             |
      | 'mod-tags'                  |

    * table userPermissions
      | name                                                               |
      | 'accounts.collection.get'                                          |
      | 'acquisitions-units.units.collection.get'                          |
      | 'addresstypes.collection.get'                                      |
      | 'addresstypes.item.post'                                           |
      | 'batch-groups.collection.get'                                      |
      | 'circulation-storage.loan-policies.collection.get'                 |
      | 'circulation-storage.loans.item.post'                              |
      | 'circulation.loans.collection.get'                                 |
      | 'comments.collection.get'                                          |
      | 'configuration.entries.collection.get'                             |
      | 'departments.collection.get'                                       |
      | 'feefineactions.collection.get'                                    |
      | 'feefines.collection.get'                                          |
      | 'finance.budgets.collection.get'                                   |
      | 'finance.exchange-rate.item.get'                                   |
      | 'finance.expense-classes.collection.get'                           |
      | 'finance.fiscal-years.collection.get'                              |
      | 'finance.fund-types.collection.get'                                |
      | 'finance.funds.collection.get'                                     |
      | 'finance.groups.collection.get'                                    |
      | 'finance.ledgers.collection.get'                                   |
      | 'finance.transactions.collection.get'                              |
      | 'fqm.entityTypes.collection.get'                                   |
      | 'fqm.entityTypes.custom.available-joins.collection.post'           |
      | 'fqm.entityTypes.custom.collection.post'                           |
      | 'fqm.entityTypes.custom.item.delete'                               |
      | 'fqm.entityTypes.custom.item.get'                                  |
      | 'fqm.entityTypes.custom.item.put'                                  |
      | 'fqm.entityTypes.item.columnValues.get'                            |
      | 'fqm.entityTypes.item.get'                                         |
      | 'fqm.materializedViews.post'                                       |
      | 'fqm.migrate.post'                                                 |
      | 'fqm.query.all'                                                    |
      | 'fqm.query.async.delete'                                           |
      | 'fqm.query.async.post'                                             |
      | 'fqm.query.async.results.get'                                      |
      | 'fqm.query.async.results.post'                                     |
      | 'fqm.query.async.results.query.get'                                |
      | 'fqm.query.async.results.sortedids.get'                            |
      | 'fqm.query.privileged.async.results.post'                          |
      | 'fqm.query.purge.post'                                             |
      | 'fqm.query.sync.get'                                               |
      | 'fqm.version.get'                                                  |
      | 'inventory-storage.alternative-title-types.collection.get'         |
      | 'inventory-storage.call-number-types.collection.get'               |
      | 'inventory-storage.classification-types.collection.get'            |
      | 'inventory-storage.contributor-name-types.collection.get'          |
      | 'inventory-storage.contributor-types.collection.get'               |
      | 'inventory-storage.electronic-access-relationships.collection.get' |
      | 'inventory-storage.holdings-note-types.collection.get'             |
      | 'inventory-storage.holdings-sources.item.post'                     |
      | 'inventory-storage.holdings-types.collection.get'                  |
      | 'inventory-storage.holdings.item.get'                              |
      | 'inventory-storage.holdings.item.post'                             |
      | 'inventory-storage.identifier-types.collection.get'                |
      | 'inventory-storage.instance-date-types.collection.get'             |
      | 'inventory-storage.instance-formats.collection.get'                |
      | 'inventory-storage.instance-note-types.collection.get'             |
      | 'inventory-storage.instance-statuses.collection.get'               |
      | 'inventory-storage.instance-types.collection.get'                  |
      | 'inventory-storage.instance-types.item.get'                        |
      | 'inventory-storage.instance-types.item.post'                       |
      | 'inventory-storage.instances.item.get'                             |
      | 'inventory-storage.instances.item.post'                            |
      | 'inventory-storage.item-note-types.collection.get'                 |
      | 'inventory-storage.items.item.get'                                 |
      | 'inventory-storage.items.item.post'                                |
      | 'inventory-storage.loan-types.collection.get'                      |
      | 'inventory-storage.loan-types.item.post'                           |
      | 'inventory-storage.location-units.campuses.item.post'              |
      | 'inventory-storage.location-units.institutions.item.post'          |
      | 'inventory-storage.location-units.libraries.collection.get'        |
      | 'inventory-storage.location-units.libraries.item.post'             |
      | 'inventory-storage.locations.collection.get'                       |
      | 'inventory-storage.locations.item.post'                            |
      | 'inventory-storage.material-types.collection.get'                  |
      | 'inventory-storage.material-types.item.post'                       |
      | 'inventory-storage.modes-of-issuance.collection.get'               |
      | 'inventory-storage.nature-of-content-terms.collection.get'         |
      | 'inventory-storage.service-points.collection.get'                  |
      | 'inventory-storage.statistical-code-types.collection.get'          |
      | 'inventory-storage.statistical-codes.collection.get'               |
      | 'inventory-storage.subject-sources.collection.get'                 |
      | 'inventory-storage.subject-types.collection.get'                   |
      | 'invoice.invoice-lines.collection.get'                             |
      | 'invoice.invoices.collection.get'                                  |
      | 'linked-data.resources.rdf.get'                                    |
      | 'lost-item-fees-policies.collection.get'                           |
      | 'manual-block-templates.collection.get'                            |
      | 'manualblocks.collection.get'                                      |
      | 'orders-storage.acquisition-methods.collection.get'                |
      | 'orders-storage.pieces.collection.get'                             |
      | 'orders-storage.po-lines.item.post'                                |
      | 'orders-storage.purchase-orders.item.post'                         |
      | 'orders-storage.titles.collection.get'                             |
      | 'orders.item.get'                                                  |
      | 'orders.po-lines.item.get'                                         |
      | 'organizations-storage.categories.collection.get'                  |
      | 'organizations-storage.organization-types.collection.get'          |
      | 'organizations-storage.organizations.item.post'                    |
      | 'organizations.organizations.collection.get'                       |
      | 'organizations.organizations.item.get'                             |
      | 'overdue-fines-policies.collection.get'                            |
      | 'owners.collection.get'                                            |
      | 'patron-blocks.user-summary.item.get'                              |
      | 'payments.collection.get'                                          |
      | 'refunds.collection.get'                                           |
      | 'search.instances.collection.get'                                  |
      | 'source-storage.records.collection.get'                            |
      | 'tags.collection.get'                                              |
      | 'transfers.collection.get'                                         |
      | 'user-tenants.collection.get'                                      |
      | 'usergroups.collection.get'                                        |
      | 'users.collection.get'                                             |
      | 'users.item.delete'                                                |
      | 'users.item.get'                                                   |
      | 'users.item.post'                                                  |
      | 'voucher.voucher-lines.collection.get'                             |
      | 'voucher.vouchers.collection.get'                                  |
      | 'waives.collection.get'                                            |

  Scenario: create tenant and users for testing
    Given call read('classpath:common/eureka/setup-users.feature')
    * call read('classpath:common/eureka/keycloak.feature@configureAccessTokenTime') { 'AccessTokenLifespance' : 3600 }

  Scenario: Add sample data for queries
    Given call read('classpath:corsair/mod-fqm-manager/features/util/add-query-data.feature')
