Feature: mod-search start

  Background:
    * url baseUrl
    * table modules
      | name                                      |
      | 'mod-search'                              |
    * table userPermissions
      | name                                                           |
      | 'search.linked-data.work.collection.get'                       |
      | 'search.linked-data.hub.collection.get'                        |
      | 'search.instances.collection.get'                              |
      | 'linked-data.resources.bib.get'                                |
      | 'linked-data.resources.bib.post'                               |
      | 'linked-data.resources.bib.put'                                |
      | 'linked-data.resources.bib.delete'                             |
      | 'linked-data.resources.bib.marc.get'                           |
      | 'linked-data.resources.reindex.post'                           |
      | 'linked-data.resources.graph.get'                              |
      | 'linked-data.resources.bib.id.get'                             |
      | 'linked-data.resources.support-check.get'                      |
      | 'linked-data.resources.preview.get'                            |
      | 'linked-data.resources.import.post'                            |
      | 'linked-data.profiles.get'                                     |
      | 'mapping-metadata.get'                                         |
      | 'inventory-storage.instances.item.post'                        |
      | 'inventory-storage.instances.item.get'                         |
      | 'inventory-storage.instances.item.put'                         |
      | 'inventory-storage.instance-types.item.post'                   |
      | 'inventory-storage.instances.item.delete'                      |
      | 'inventory-storage.preceding-succeeding-titles.collection.get' |
      | 'inventory-storage.preceding-succeeding-titles.item.get'       |
      | 'inventory.instances.item.get'                                 |
      | 'inventory.instances.item.put'                                 |
      | 'source-storage.snapshots.post'                                |
      | 'source-storage.records.post'                                  |
      | 'source-storage.records.put'                                   |
      | 'source-storage.records.formatted.item.get'                    |
      | 'marc-records-editor.item.post'                                |
      | 'marc-records-editor.item.put'                                 |
      | 'inventory-storage.authority-source-files.item.post'           |
      | 'browse.authorities.collection.get'                            |
      | 'source-storage.records.formatted.item.get'                    |
      | 'specification-storage.specifications.collection.get'          |
      | 'specification-storage.specification.rules.collection.get'     |
      | 'specification-storage.specification.rules.item.patch'         |

  Scenario: Module search init
    Given call read('classpath:common/setup-users.feature@installModules')
    Given call read('classpath:common/setup-users.feature@addDesiredPermission')
    Given call read('classpath:common/setup-users.feature@createTestUsers')
    Given call read('classpath:common/setup-users.feature@specifyUserCreds')
    Given call read('classpath:common/setup-users.feature@setAdminPermissions')
    Given call read('classpath:common/setup-users.feature@addUserPermissions')
    Given call read('classpath:common/setup-users.feature@enableAuthTokenModule')