name: Maven Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: actions/setup-java@v6
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn -DskipTests clean install
